image: python:3.7.5-buster

stages:
  - build
  - distribute

.common: &common
  only:
    - tags
  tags:
    - backend-docker

build:
  <<: *common
  stage: build
  when: always
  artifacts:
    paths:
      - dist/
    expire_in: 3 days
  script: >
    [[ $(awk -F= '/version/{gsub("^[ ]+|\"|,","");print $2}' setup.py) != $CI_COMMIT_TAG  ]] && echo Version mismatch && exit 1;

    python3 setup.py bdist_wheel

distribute:
  <<: *common
  stage: distribute
  when: on_success
  dependencies:
    - build
  script: >
    pip install twine &&
    twine upload \
      -u $PYPI_USER \
      -p $PYPI_PASSWORD \
      --repository-url https://$PYPI_HOST/$PYPI_URI/ \
      dist/*
